// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// log_mh_cpp
List log_mh_cpp(int n, NumericVector par0, NumericVector sigmas, Function ll, Function lprior, Function lsampler, Function lsample_dens);
RcppExport SEXP _mcmcpack_log_mh_cpp(SEXP nSEXP, SEXP par0SEXP, SEXP sigmasSEXP, SEXP llSEXP, SEXP lpriorSEXP, SEXP lsamplerSEXP, SEXP lsample_densSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par0(par0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigmas(sigmasSEXP);
    Rcpp::traits::input_parameter< Function >::type ll(llSEXP);
    Rcpp::traits::input_parameter< Function >::type lprior(lpriorSEXP);
    Rcpp::traits::input_parameter< Function >::type lsampler(lsamplerSEXP);
    Rcpp::traits::input_parameter< Function >::type lsample_dens(lsample_densSEXP);
    rcpp_result_gen = Rcpp::wrap(log_mh_cpp(n, par0, sigmas, ll, lprior, lsampler, lsample_dens));
    return rcpp_result_gen;
END_RCPP
}
// mh_cpp
List mh_cpp(int n, NumericVector par0, NumericVector sigmas, Function likelihood, Function prior, Function sampler, Function sample_dens);
RcppExport SEXP _mcmcpack_mh_cpp(SEXP nSEXP, SEXP par0SEXP, SEXP sigmasSEXP, SEXP likelihoodSEXP, SEXP priorSEXP, SEXP samplerSEXP, SEXP sample_densSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par0(par0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigmas(sigmasSEXP);
    Rcpp::traits::input_parameter< Function >::type likelihood(likelihoodSEXP);
    Rcpp::traits::input_parameter< Function >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< Function >::type sampler(samplerSEXP);
    Rcpp::traits::input_parameter< Function >::type sample_dens(sample_densSEXP);
    rcpp_result_gen = Rcpp::wrap(mh_cpp(n, par0, sigmas, likelihood, prior, sampler, sample_dens));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mcmcpack_log_mh_cpp", (DL_FUNC) &_mcmcpack_log_mh_cpp, 7},
    {"_mcmcpack_mh_cpp", (DL_FUNC) &_mcmcpack_mh_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_mcmcpack(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
