# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_mh_cpp <- function(n, par0, sigmas, ll, lprior, lsampler, lsample_dens) {
    .Call(`_mcmcpack_log_mh_cpp`, n, par0, sigmas, ll, lprior, lsampler, lsample_dens)
}

mh_cpp <- function(n, par0, sigmas, likelihood, prior, sampler, sample_dens) {
    .Call(`_mcmcpack_mh_cpp`, n, par0, sigmas, likelihood, prior, sampler, sample_dens)
}

